config:
  host: devx-helloworld-springboot-1lwt8.nonp-dev-4.use1.eng-nonprod.flexport.internal
  namespace: devx-helloworld-springboot-1lwt8-dev
  image:
    name: artifactory.flexport.io/devx-helloworld-springboot-1lwt8-docker-dev-local/devx-helloworld-springboot-1lwt8
    tag: 0.0.1-SNAPSHOT
